apiVersion: v1
kind: Service
metadata:
  name: tornado-svc
  labels:
    app: tornado
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8888
  selector:
    app: tornado
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: tornado-deploy
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: tornado
    spec:
      containers:
      - name: tornado
        image: registry.alauda.cn/ljy2010a/docker-tornado:latest
        ports:
        - containerPort: 8888
